package com.example.bloom_app.ui.theme


import androidx.compose.ui.graphics.Color

val BloomPrimary = Color(0xFFA0616A)
val BloomPrimaryDark = Color(0xFF8B4F57)
val BloomBackground = Color(0xFFFFF8F6)
val BloomSurface = Color(0xFFFFFFFF)
val BloomOnSurface = Color(0xFF1A1A1A)
val BloomSecondary = Color(0xFFD4A19A)
val BloomAccent = Color(0xFFC17B73)
val BloomLightPink = Color(0xFFF5E6E0)
val BloomCream = Color(0xFFFFF5F0)
val BloomTextDark = Color(0xFF2D2D2D)
val BloomTextLight = Color(0xFF8A8A8A)
val BloomGold = Color(0xFFC9A96E)
val BloomPetalDark = Color(0xFF8B4513)
val BloomPetalMedium = Color(0xFFA0616A)
val BloomPetalLight = Color(0xFFC8847A)
val BloomCenter = Color(0xFFC9A96E)
val BloomCardBackground = Color(0xFFFAF0EC)
val BloomDivider = Color(0xFFE8D5CF)
val BloomIndicatorActive = Color(0xFFA0616A)
val BloomIndicatorInactive = Color(0xFFE8D5CF)
val BloomToggleTrackOn = Color(0xFFA0616A)
val BloomToggleTrackOff = Color(0xFFD4D4D4)
val BloomGreen = Color(0xFF4CAF50)
val BloomBlue = Color(0xFF5B9BD5)
val BloomOrange = Color(0xFFE8945A)
val BloomPurple = Color(0xFF9B72AA)
val BloomYellow = Color(0xFFE8C84A)
val BloomRed = Color(0xFFE85A5A)
val BloomTeal = Color(0xFF5BB5A2)